### ISSUE TITLE
ci(kitchen) service tests should verify a service common across platforms

### ISSUE THREAD

**Issue by javierbertoli** [saltstack-formulas/template-formula#104]
On the initial incarnations of the tests, we added `systemd-udevd` as the service to check. Now that we added `centos-6` platform, which is `SysV`, we should probably modify the test example to verify some other service, perhaps `crond`

**Comment by myii** [comment]
Isn't it possible to adapt the existing solution to check for the relevant version of `udev` on `centos-6`?

**Comment by baby-gnu** [comment]
Maybe we could use en entry in `osfingermap.yaml` for the service to check depending on the platform, like with the package and configuration file?

**Comment by daks** [comment]
I second the idea of @baby-gnu, we could have a `case` statement (like this https://github.com/saltstack-formulas/collectd-formula/blob/master/test/integration/default/controls/config.rb#L6) to specify different service check

**Comment by javierbertoli** [comment]
@daks Yes, considered that. Just wanted to keep the tests the simplest as possible.

But OTOH, it's not a big deal to add a `case` statement, and it can also be a nice example of the way to do testing.

**Comment by myii** [comment]
Potential solution provided at #105.
