### ISSUE TITLE
missing issues with 'systemd-formula'

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/template-formula#111]
no issues possible on systemd-formula, I don't have the rights to add it...

**Comment by johnkeates** [comment]
looks like only core and owners can do that :(

**Comment by myii** [comment]
@aboe76 When running into problems, I usually just ping gtmanfred on Slack and get the resolution.  I've just pinged, so let's see the response.

**Comment by aboe76** [comment]
@myii I think the systemd-formula has some more issues, with permissions...

**Comment by myii** [comment]
@aboe76 Yes, the `semantic-release` user needs write permissions, I've also just requested those.  Is there something else as well?

**Comment by n-rodriguez** [comment]
> no issues possible on systemd-formula

neither on rkhunter formula

**Comment by myii** [comment]
Et voilà:

@aboe76 https://github.com/saltstack-formulas/systemd-formula/issues
@n-rodriguez https://github.com/saltstack-formulas/rkhunter-formula/issues
