### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/template-formula#170]
https://github.com/saltstack-formulas/template-formula/blob/18a056da928e0c071a5fc1dcc09bbcaa538a62b2/template/osarchmap.yaml#L19

I think we should use

```yml
'386':
  arch: '386'
```
instead of

```yml
386:
  arch: 386
```
to avoid string/integer bugs while comparing values.

@myii what do you think?

**Comment by myii** [comment]
@n-rodriguez Definitely worth considering.  Reminds me of another `yamllint` rule we could look at in the long run:

* https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings

What's your take on this @noelmcloughlin?
