### ISSUE TITLE
Improvements (enhancement backlog?) needed

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/template-formula#18]
It would be nice to be able to produce working formula rapidly from a template.  

For example this template is not supporting repo / release / container mediums for deployment. But modern digital companies are heavily using these channels for DevOps and Cloud Native deployments and solutions.  It would be good to improve this formula so people can producer a formula rapidly.

Features:
- release support:  archive download, checksum, extraction of tarballs.
- repo support: git latest from url
- repo-make support:  previous plus make command.
- container
- every **init** state having a corresponding **clean** state!!!

There are lot of tools (i.e. chrome,  gnuPG. scala, VS, git-review,, postman, firefox developer edition, pulse secure, citrix workspace, etc) and technologies (quicc, gprc, or whatever) that could be hosted but developing formulas is too hard ... template-formula should be improved!!!

**Comment by aboe76** [comment]
@noelmcloughlin you can try this:
https://github.com/slafs/cookiecutter-saltstack-formula

**Comment by noelmcloughlin** [comment]
Thanks @aboe76  I'll have a look at that repo.
