### ISSUE TITLE
[BUG] Debian Docker image should have dbus installed

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/template-formula#201]
### Pillar / config used

---

### Describe the bug

If `dbus` is missing Inspec tests fail with error (I had to dig in Inspec and add some debug logs to find it) : 

```sh
nicolas@laptop:~/PROJECTS/saltstack$ bin/kitchen verify default-debian-9-2019-2-py3
-----> Starting Test Kitchen (v2.5.3)
-----> Verifying <default-debian-9-2019-2-py3>...
       Loaded tests from {:path=>".home.nicolas.PROJECTS.saltstack.test.integration.default"} 
#<Inspec::Resources::Systemd:0x00007f00e8289cc8 @service_ctl="systemctl", @inspec=Inspec::Backend::Class @transport=Train::Transports::SSH::Connection>
#<Inspec::Resources::Systemd:0x00007f00e8289cc8 @service_ctl="systemctl", @inspec=Inspec::Backend::Class @transport=Train::Transports::SSH::Connection>
#<#<Class:0x00007f00e822dea0>:0x00007f00e85fbca8 @resource_skipped=false, @resource_failed=false, @supports=[{:platform=>"unix"}, {:platform=>"windows"}], @resource_exception_message=nil, @__backend_runner__=Inspec::Backend::Class @transport=Train::Transports::SSH::Connection, @__resource_name__=:command, @command="systemctl show --no-pager --all prometheus-alertmanager">
1
Failed to connect to bus: No such file or directory
```

Edit: it fails on Debian 9 and Debian 10

**Comment by myii** [comment]
@n-rodriguez We've encountered this situation before in the `timezone-formula`:

* [Issue and discussion about `dbus`](https://github.com/saltstack-formulas/timezone-formula/issues/11)
* [Commit adding `dbus` to the formula](https://github.com/saltstack-formulas/timezone-formula/pull/23/commits/ff66e5fd10c06da5dbe2ae2320fd8f2eddc459f7)
* [Specific `dbus` commit for Gentoo](https://github.com/saltstack-formulas/timezone-formula/commit/0e2da3600c85e5024ffa04cb1fdade129dd24089)

I recall discussing the idea about including `dbus` in the pre-salted images but the I believe the conclusion was that formulas should be responsible for installing it if they need it.  Unfortunately, can't find where we had this conversation, though.

Hopefully @javierbertoli will be able to shed some more light into this issue.

**Comment by javierbertoli** [comment]
Yeah, I recall we discussed it but, if **you** can't find the history of that discussion, I'm totally sure I won't ever be able to either :smile: 

In any case, what you said is more or less the conclusion at which we arrived at that moment: the idea of the images is to ease and speed formulas' testing, pre-installing salt and a few testing tools in them. But it **should not** be a task of the images to provide/install packages that the **formula** depends on.

In this case, I'm not sure how is this error happening. @n-rodriguez, can you provide some more light on what you're testing (which formula, what app), to better determine where does this issue belong?

If you're testing directly this same `template` formula, then perhaps is something that we should add to the images. But reading the piece of logs you pasted, it seems that `dbus` is a dependency required to run and test prometheus? (I'm trying to guess here)

I'd be grateful if you can provide more details about your testing environment.

**Comment by n-rodriguez** [comment]
> But it **should not** be a task of the images to provide/install packages that the **formula** depends on.

It's not a formula dependency but more a system one. Debian uses systemd which depends on dbus.
I don't know why dbus is not installed by default by Debian when installing systemd but IMHO it's a bug.

**Comment by n-rodriguez** [comment]
> can you provide some more light on what you're testing (which formula, what app), to better determine where does this issue belong?

I'm testing an enterprise repository which uses prometheus formula and found some bugs around it.

**Comment by n-rodriguez** [comment]
>  I don't know why dbus is not installed by default by Debian when installing systemd but IMHO it's a bug.

it's a recommended package : https://packages.debian.org/fr/buster/systemd

**Comment by javierbertoli** [comment]
I see. As you mention, `dbus` is a _recommendation_ and not a _requirement/dependency_ to use systemd. 

When building the images, we are [explicitly skipping recommended packages](https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/blob/master/Dockerfile.apt#L15-16) to keep images slim. As Debian does not consider **dbus** as a hard requirement to run **systemd**, it's not being installed.

If I understand you, the formula _converges_ correctly but _testing_ fails when **inspec** run. Is is possible for you to paste the failing test code, or the place in inspec code where you think it's failing?

I'd like to  the best place to add the missing dependency: as other formulas are not failing with the current images, I suspect this might still be a dependency to be added in some specific formulas that depend on d-bus messaging.

My reasoning is (I can be totally wrong, ofc):

* if the error happens with a _native_ inspec resource (other than _command_), then I understand `dbus` should be added in the images for the reasons I mentioned previously.

OTOH, if it's with a _command_ resource (which invokes OS commands for a specific test), then it either should be added:

* as a package that the formula should install (because it's required for the intrinsic functioning of the application being managed with salt), or
* [as a formula dependency for testing purposes](https://github.com/saltstack-formulas/logrotate-formula/blob/master/test/salt/states/cron.sls) because it's needed for the very specific tests for this specific formula (but not for other formulas), or
* as a formula dependency for testing purposes in **the template formula**, because the kind of test that is failing is a "generic" command run with inspec.

Hope I was clear with what I tried to say :yum:

**Comment by n-rodriguez** [comment]
> If I understand you, the formula _converges_ correctly but _testing_ fails when **inspec** run. 

Right 

> Is is possible for you to paste the failing test code, or the place in inspec code where you think it's failing?

```ruby
  describe service('prometheus') do
    it { should be_enabled }
    it { should be_running }
  end
```

Actually there are 2 issues here :

**On Debian 9 :**

It fails because `dbus` is missing. Inspec fails here https://github.com/inspec/inspec/blob/master/lib/inspec/resources/service.rb#L286

`cmd.stderr` says : `Failed to connect to bus: No such file or directory`

Installing `dbus` solves the issue

**On Debian 10 :**

It fails because `dbus` is missing.

Then it fails because of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964926

The command sent by Inspec works : `systemctl show --no-pager --all prometheus-alertmanager`

but it ends with `Failed to parse bus message: Invalid argument` so this line breaks https://github.com/inspec/inspec/blob/master/lib/inspec/resources/service.rb#L307 because it cannot parse the output

**Comment by myii** [comment]
_May_ be relevant here, in respect to reintroducing `systemd` to a formula in `kitchen.yml`:

* `systemd-formula`: [ci(kitchen): reinstall `udev` since removed from pre-salted images](https://github.com/saltstack-formulas/systemd-formula/pull/55/files).

**Comment by n-rodriguez** [comment]
I got the same issue with `telegraf-formula` :

run `bin/kitchen verify default-debian-10-master-py3` got :

```sh
-----> Starting Test Kitchen (v2.6.0)
-----> Verifying <default-debian-10-master-py3>...
       Loaded default 
Failed to parse bus message: Invalid argument
Failed to parse bus message: Invalid argument

Profile: telegraf formula (default)
Version: (not specified)
Target:  ssh://kitchen@localhost:32796

  ✔  Telegraf package: should be installed
     ✔  System Package telegraf is expected to be installed
  ×  Telegraf service: should be running and enabled (2 failed)
     ×  Service telegraf is expected to be enabled
     expected that `Service telegraf` is enabled
     ×  Service telegraf is expected to be running
     expected that `Service telegraf` is running
  ✔  Telegraf configuration: should match desired lines
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.diskio]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.kernel]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.mem]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.processes]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.swap]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.system]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[outputs.discard]"
```

**Comment by n-rodriguez** [comment]
I run Arch Linux

```sh
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 136
 Server Version: 19.03.12-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.1-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.491GiB
 Name: tchoum-laptop
 ID: JUYC:HCXJ:Z6T4:I5FS:AYFO:5KWO:HCIB:6KEV:TGQN:52M3:WLNG:DS4L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: nicoladmin
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  git.vigilience.corp:4567
  127.0.0.0/8
 Live Restore Enabled: false
```

systemd 

```sh
systemd 246 (246.1-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by n-rodriguez** [comment]
I triggered a CRON build on Travis for `telegraf-formula` and it works https://travis-ci.com/github/saltstack-formulas/telegraf-formula

**Comment by n-rodriguez** [comment]
Travis uses

Docker :

```sh
docker version

Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by n-rodriguez** [comment]
At first I thought I was due to a change in the Docker image because the latest build of `telegraf-formula` was green. But the latest build was 3 months ago. 

That's why I triggered a cron build against the latest commit of master : it forces a build with a fresh Docker image. It the bug is in the Docker image it should fail.

But tests still pass, so the bug must be around local config.

**Comment by n-rodriguez** [comment]
@myii maybe we should enable Travis cron build to avoid what I described above : Docker images has been updated but tests are not run on new images. wdyt? If so we should add a test in `.travis.yml` to not trigger a new release on CRON jobs.

**Comment by myii** [comment]
> I got the same issue with `telegraf-formula` :
> 
> run `bin/kitchen verify default-debian-10-master-py3` got :
> 
> ```shell
> -----> Starting Test Kitchen (v2.6.0)
> -----> Verifying <default-debian-10-master-py3>...
>        Loaded default 
> Failed to parse bus message: Invalid argument
> Failed to parse bus message: Invalid argument
> 
> Profile: telegraf formula (default)
> Version: (not specified)
> Target:  ssh://kitchen@localhost:32796
> 
>   ✔  Telegraf package: should be installed
>      ✔  System Package telegraf is expected to be installed
>   ×  Telegraf service: should be running and enabled (2 failed)
>      ×  Service telegraf is expected to be enabled
>      expected that `Service telegraf` is enabled
>      ×  Service telegraf is expected to be running
>      expected that `Service telegraf` is running
>   ✔  Telegraf configuration: should match desired lines
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.diskio]"
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.kernel]"
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.mem]"
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.processes]"
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.swap]"
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.system]"
>      ✔  File /etc/telegraf/telegraf.conf content is expected to include "[outputs.discard]"
> ```

@n-rodriguez I'm just about to try the build locally on my machine.

> @myii maybe we should enable Travis cron build to avoid what I described above : Docker images has been updated but tests are not run on new images. wdyt? If so we should add a test in `.travis.yml` to not trigger a new release on CRON jobs.

This sounds like it fits in with the direction that we've been heading in:

* Until fairly recently, I was running weekly tests across all formulas and collecting the results in the [CI stream in Zulip](https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI) (can log in using the GitHub integration).
* Another aspect of this has been discussed in the working group meetings: since SaltStack is moving towards Tiamat builds, we've generally decided to make these our main focus across formulas' testing in the near future.
* The final part of this jigsaw would be to enable cron builds across all formulas to run weekly and collect all pass/failure results into Zulip.

Thanks for all of the feedback so far!

**Comment by n-rodriguez** [comment]
>     * The final part of this jigsaw would be to enable cron builds across all formulas to run weekly and collect all pass/failure results into Zulip.

ok. In the mean time why not enable monthly cron on Travis? (it should be a matter of 2 or 3 clicks and a few bit in `travis.yml`)

**Comment by n-rodriguez** [comment]
https://docs.travis-ci.com/user/cron-jobs/#detecting-builds-triggered-by-cron

**Comment by myii** [comment]
@n-rodriguez All OK at this end:

```ruby
Profile: telegraf formula (default)
Version: (not specified)
Target:  ssh://kitchen@localhost:32768

  ✔  Telegraf configuration: should match desired lines
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.diskio]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.kernel]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.mem]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.processes]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.swap]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[inputs.system]"
     ✔  File /etc/telegraf/telegraf.conf content is expected to include "[outputs.discard]"
  ✔  Telegraf service: should be running and enabled
     ✔  Service telegraf is expected to be enabled
     ✔  Service telegraf is expected to be running
  ✔  Telegraf package: should be installed
     ✔  System Package telegraf is expected to be installed


Profile Summary: 3 successful controls, 0 control failures, 0 controls skipped
Test Summary: 10 successful, 0 failures, 0 skipped
       Finished verifying <default-debian-10-master-py3> (0m0.60s).
```

**Comment by n-rodriguez** [comment]
> @n-rodriguez All OK at this end:

what is your distro?

**Comment by myii** [comment]
> > @n-rodriguez All OK at this end:
> 
> what is your distro?

```sls
#  salt -V
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-42-generic
         system: Linux
        version: Ubuntu 20.04 focal
```

**Comment by n-rodriguez** [comment]
And Docker and systemd?

**Comment by myii** [comment]
@n-rodriguez Here:

```sls
$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

$ systemd --version
systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybr
id
```

**Comment by n-rodriguez** [comment]
It works on Debian 10 :

Docker :

```sh
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 33
 Server Version: 19.03.12
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.32GiB
 Name: cloud
 ID: KOWN:EKKX:55F6:TONG:JMJD:ZX5Z:RD5C:U3JQ:CCHG:2LN5:M2Q7:H6IS
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

systemd :

```sh
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by n-rodriguez** [comment]
```sh
# n-rodriguez (local)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
Kernel Version: 5.8.1-arch1-1

# myii
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4       +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
Kernel Version: 5.4.0-42-generic

# n-rodriguez (remote)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4       +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
 Kernel Version: 4.19.0-10-amd64
```

**Comment by n-rodriguez** [comment]
Here the reason why all this mess : https://github.com/systemd/systemd-stable/commit/5325d280ab8468b981014c700d1d6cc1f01a3c02
