### ISSUE TITLE
[BUG]  convert.sh script does not change gitlab-ci stuff

### ISSUE THREAD

**Issue by codeboyQ2n5ha45** [saltstack-formulas/template-formula#231]
### Describe the bug

When you run the bin/convert.sh script to create your formula, the script does not change the 9-10:
``` 
only_branch_master_parent_repo: &only_branch_master_parent_repo
    - 'master@saltstack-formulas/template-formula'
```
And does not change lines 57-58:
```
- 'git remote add upstream
       https://gitlab.com/saltstack-formulas/template-formula.git'
```
It should change it to the name of your formula so that gitlab-ci  runs.

**Comment by myii** [comment]
Thanks for the report, @codeboyQ2n5ha45.  Hopefully @dafyddj or myself will fix this soon.

**Comment by noelmcloughlin** [comment]
Same issue with `test/integration/default/controls /config.rb`

**Comment by myii** [comment]
Also:

https://github.com/saltstack-formulas/template-formula/blob/d9ee80784bd73ceb425b8c12103381a929d86178/release.config.js#L3

**Comment by dafyddj** [comment]
> Same issue with `test/integration/default/controls /config.rb`

This seems unrelated to this bug, can you open another issue?
