### ISSUE TITLE
init.sls uses 'absolute path' to include states

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/template-formula#51]
In init.sls https://github.com/saltstack-formulas/template-formula/blob/master/template/init.sls#L4 we can see

```
include:
  - template.install
  - template.config
  - template.service
```

It uses 'absolute path' to include other states. In our private formulas, we tend to use the following pattern with relative paths
```
include:
  - .install
  - .config
  - .service
```
and it works well, and lets you name the formula as you want _(eg: if you 'vendor' it in your repository)_.

If we don't identify any problem with this pattern, I think we should use it.

I can make a PR if we agree to change this.

**Comment by myii** [comment]
@daks Thanks for this but you're too late!  It has already been proposed in #48.  That will probably be merged in shortly.  Please take a look over that PR, there are substantial changes and your feedback would be appreciated.
