### ISSUE TITLE
TOFSv2: Change duplicate use of `files`; use `templates` list instead

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/template-formula#55]
The current implementation uses `files` twice.

Here:

https://github.com/saltstack-formulas/template-formula/blob/c71915ed1e38d72c38360d409ddcffd01a61f557/pillar.example#L31-L32

And here:

https://github.com/saltstack-formulas/template-formula/blob/c71915ed1e38d72c38360d409ddcffd01a61f557/pillar.example#L34-L37

Since the second one is a list of templates to use, I suggest this is changed to:

```sls
    # templates:
    #   template-config:
    #     - 'example_alt.tmpl'
    #     - 'example_alt.tmpl.jinja'
```

The impact is fairly significant, since this needs to be done throughout:

1. `pillar.example`
1. `macros.jinja`
1. `TOFS_pattern.md`
1. All formulas that have already adapted to TOFSv2

Since TOFSv2 is very new, this change needs to be brought in ASAP.  It hardly can be in use right now but it soon could be.

**Comment by myii** [comment]
@aboe76 Is it too late to make this change in `systemd-formula`?

**Comment by baby-gnu** [comment]
I think this is done by #76 and this issue can be closed. No?

**Comment by myii** [comment]
@baby-gnu Yes, thank you!
